export const Categories = [
	{ id: 'language', name: 'Programming Language' },
	{ id: 'frontend', name: 'Frontend Development' },
	{ id: 'backend', name: 'Backend Development' },
	{ id: 'framework', name: 'Framework' },
	{ id: 'database', name: 'Database System' },
	{ id: 'software', name: 'Software' },
	{ id: 'tool', name: 'Development Tool' },
	{ id: 'os', name: 'Operating System' },
	{ id: 'design', name: 'Design Tool' },
	{ id: 'hosting', name: 'Hosting Platform' },
	{ id: 'editor', name: 'Code Editor' },
	{ id: 'ide', name: 'IDE' },
	{ id: 'scripting', name: 'Scripting Language' },
	{ id: 'library', name: 'Software Library' },
	{ id: 'misc', name: 'Miscellaneous' },
];