import HeroSection from 'components/herosection';
import Navbar from 'components/navbar';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>{"Nimish Jain's Portfolio"}</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='min-h-screen min-w-full'>
				<HeroSection />
				<Navbar />
				<HeroSection />
				<HeroSection />
			</main>
		</div>
	);
};

export default Home;
