import About from 'components/about';
import HeroSection from 'components/herosection';
import Navbar from 'components/navbar';
import Projects from 'components/projects';
import Research from 'components/research';
import Skills from 'components/skills';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>{"Nimish Jain's Portfolio"}</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='min-h-screen min-w-full'>
				<HeroSection />
				<Navbar />
				<About />
				<Skills />
				<Projects />
				<Research />
			</main>
		</div>
	);
};

export default Home;
