import {
	FaAngular,
	FaApple,
	FaCss3,
	FaDiscord,
	FaFigma,
	FaGitAlt,
	FaGithub,
	FaHtml5,
	FaJava,
	FaJs,
	FaNodeJs,
	FaPython,
	FaReact,
	FaSass,
	FaUbuntu,
	FaWindows,
} from 'react-icons/fa';
import {
	SiExpress,
	SiIntellijidea,
	SiJquery,
	SiManjaro,
	SiMongodb,
	SiMysql,
	SiTailwindcss,
	SiVisualstudiocode,
} from 'react-icons/si';
import { TbBrandNextjs } from 'react-icons/tb';
import CIcon from '../assets/icons/c-original.svg';
import CppIcon from '../assets/icons/cplusplus-original.svg';
import Matlab from '../assets/icons/matlab.svg';

export const allSkills = [
	{
		name: 'C',
		icon: <CIcon height='1em' />,
		bgcolor: 'rgb(4, 99, 172)',
		link: 'https://devdocs.io/c/',
	},
	{
		name: 'C++',
		icon: <CppIcon height='1em' />,
		bgcolor: '#af0443',
		link: 'https://devdocs.io/cpp/',
	},
	{
		name: 'Java',
		icon: <FaJava />,
		bgcolor: '#f89820',
		link: 'https://docs.oracle.com/en/java/',
		color: 'black',
	},
	{
		name: 'Python',
		icon: <FaPython />,
		bgcolor: '#306998',
		link: 'https://docs.python.org/3/',
	},
	{
		name: 'HTML',
		icon: <FaHtml5 />,
		bgcolor: '#E34F26',
		link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
	},
	{
		name: 'CSS',
		icon: <FaCss3 />,
		bgcolor: '#264de4',
		link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
	},
	{
		name: 'JavaScript',
		icon: <FaJs />,
		bgcolor: '#F0DB4F',
		link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
		color: '#323330',
	},
	{
		name: 'Next.js',
		icon: <TbBrandNextjs />,
		bgcolor: 'white',
		link: 'https://nextjs.org/',
		color: 'black',
	},
	{
		name: 'React.js',
		icon: <FaReact />,
		bgcolor: '#61DBFB',
		link: 'https://reactjs.org/docs/getting-started.html',
		color: 'black',
	},
	{
		name: 'Angular.js',
		icon: <FaAngular />,
		bgcolor: '#a6120d',
		link: 'https://angularjs.org/',
	},
	{
		name: 'Node.js',
		icon: <FaNodeJs />,
		bgcolor: '#3c873a',
		link: 'https://nodejs.org/en/',
	},
	{
		name: 'Express.js',
		icon: <SiExpress />,
		bgcolor: '#fff',
		link: 'https://expressjs.com/',
		color: 'black',
	},
	{
		name: 'MongoDB',
		icon: <SiMongodb />,
		bgcolor: '#4DB33D',
		link: 'https://www.mongodb.com/docs/',
		color: '#3F3E42',
	},
	{
		name: 'Discord.js',
		icon: <FaDiscord />,
		bgcolor: 'rgb(88 101 242)',
		link: 'https://discord.js.org/',
	},
	{
		name: 'Matlab',
		icon: <Matlab height='1em' />,
		bgcolor: '#f51300',
		link: 'https://mathworks.com/help/matlab/',
	},
	{
		name: 'Sass',
		icon: <FaSass />,
		bgcolor: '#CD6799',
		link: 'https://sass-lang.com/',
	},
	{
		name: 'Tailwind CSS',
		icon: <SiTailwindcss />,
		bgcolor: '#38bdf8',
		link: 'https://tailwindcss.com/',
		color: 'black',
	},
	{
		name: 'JQuery',
		icon: <SiJquery />,
		bgcolor: '#0769AD',
		link: 'https://jquery.com/',
	},
	{
		name: 'MySQL',
		icon: <SiMysql />,
		bgcolor: '#f29111',
		link: 'https://www.mysql.com/',
		color: '#2c2c2c',
	},
	{
		name: 'Git',
		icon: <FaGitAlt />,
		bgcolor: '#F1502F',
		link: 'https://git-scm.com/doc',
	},
	{
		name: 'GitHub',
		icon: <FaGithub />,
		bgcolor: 'white',
		link: 'https://github.com',
		color: '#171515',
	},
	{
		name: 'VS Code',
		icon: <SiVisualstudiocode />,
		bgcolor: '#0065A9',
		link: 'https://code.visualstudio.com/',
	},
	{
		name: 'IntelliJ',
		icon: <SiIntellijidea />,
		bgcolor: '#ff318c',
		link: 'https://www.jetbrains.com/idea/',
	},
	{
		name: 'Figma',
		icon: <FaFigma />,
		bgcolor: '#a159ff',
		link: 'https://www.figma.com/',
	},
	{
		name: 'Ubuntu (Debian)',
		icon: <FaUbuntu />,
		bgcolor: '#E95420',
		link: 'https://ubuntu.com/',
	},
	{
		name: 'Manjaro (Arch)',
		icon: <SiManjaro />,
		bgcolor: '#34BE5B',
		link: 'https://manjaro.org/',
		color: 'black',
	},
	{
		name: 'MacOS',
		icon: <FaApple />,
		bgcolor: 'white',
		link: 'https://apple.com',
		color: 'black',
	},
	{
		name: 'WindowsOS',
		icon: <FaWindows />,
		bgcolor: '#00a4ef',
		link: 'https://www.microsoft.com/en-in/windows',
	},
];
